algoritmo "semnome"
// Função :
// Autor :
// Data : 25/03/2018
// Seção de Declarações 
var
num: inteiro
inicio
// Seção de Comandos 
escreval("Digite um número")
leia(num)
se num>0 entao
escreval("o numero mais cinco é:", num+5)
fimse

se num<0 entao
escreval("O número menos dez é:", num-10)
fimse

se num=0 entao
escreva("O número multiplicado por tres é", num*3)
fimse

fimalgoritmo
