algoritmo "dias_semana"

var

diasemana: caractere

inicio

escreva ("Digite um número de 1 à 7: ")
leia (diasemana)

escolha diasemana
caso "1"
escreva ("Domingo")
caso "2"
escreva ("Segunda")
caso "3"
escreva ("Terça")
caso "4"
escreva ("Quarta")
caso "5"
escreva ("Quinta")
caso "6"
escreva ("Sexta")
caso "7"
escreva ("Sábado")

outrocaso
escreva("Número Inválido")
fimescolha

fimalgoritmo
