algoritmo "tres_numeros_inteiros_positivos_calcular"
// Função : ler três números inteiros positivos e calcular
// Autor : Meridiane Schessoff Nunes
// Data : 17/03/2018
// Seção de Declarações
var
A, B, C, resultado: real
inicio
// Seção de Comandos
escrever('Digite o valor de A:')
ler(A)
escrever('Digite o valor de B:')
ler(B)
escrever('Digite o valor de C:')
ler(C)
resultado=(A+B)*(A+B)+(B+C)*(B+C)/2
escrever('O resultado é:', resultado)
fimalgoritmo
