algoritmo "semnome"
//Crie um algoritmo que leia um número do usuário e desenhe o seguinte
//padrão na tela.
//Ex: para o número = 5
//*
//**
//***
//****
//*****
Var
// Seção de Declarações das variáveis
 in: inteiro
 j, k: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 leia(in)
 para j de 1 ate in passo 1 faca
 para k de 1 ate j faca
 escreva("*")
 fimpara
 escreval("")
 fimpara
Finaalgoritmo
