algoritmo "semnome"
// Função :
// Autor :
// Data : 05/05/2018
// Seção de Declarações 
var
num1: inteiro
num2: inteiro
mult: inteiro

inicio
para num1 de 1 ate 10 passo 1 faca
escreval ("tabuada", num1)

              para num2 de 1 ate 10 passo +1 faca
              escreva (num1, "x", num2, "=")
              escreval(num1*num2)
              fimpara
              
fimpara

fimalgoritmo
